[PHP]
engine = On
short_open_tag = Off
precision = 16
output_buffering = 4096
zlib.output_compression = Off
implicit_flush = Off
unserialize_max_depth = 4096
serialize_precision = -1
disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,exec,passthru,shell_exec,system,proc_open,popen,curl_multi_exec,show_source
disable_classes =
zend.enable_gc = On
expose_php = Off
max_execution_time = 30
max_input_time = 60
memory_limit = 256M
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = Off
display_startup_errors = Off
log_errors = On
log_errors_max_len = 1024
ignore_repeated_errors = Off
ignore_repeated_source = Off
report_memleaks = On
html_errors = Off
error_log = /dev/stderr
post_max_size = 100M
upload_max_filesize = 100M
max_file_uploads = 20
default_charset = UTF-8
file_uploads = On
allow_url_fopen = On
allow_url_include = Off
enable_dl = Off
date.timezone = UTC

[CLI Server]
cli_server.color = On

[OpCache]
opcache.enable = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 10000
opcache.revalidate_freq = 2
opcache.fast_shutdown = 1
opcache.enable_cli = 1

[Session]
session.save_handler = redis
session.save_path = "tcp://redis:6379?prefix=astra_os_session:"
session.use_strict_mode = 1
session.use_cookies = 1
session.use_only_cookies = 1
session.name = astra_os_session
session.cookie_httponly = 1
session.cookie_samesite = "Lax"
session.sid_length = 64
session.sid_bits_per_character = 6

[XDebug]
xdebug.mode = off
xdebug.start_with_request = trigger
xdebug.max_nesting_level = 512
