apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: astra-os-backup
  namespace: astraos
rules:
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]