apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: astra-os-podmonitor
  namespace: astraos
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: astra-os
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
      scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace