apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: astraos-storage
  namespace: astraos
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs-sc
