apiVersion: v1
kind: Service
metadata:
  name: astraos-app
  namespace: astraos
  labels:
    app: astraos
    component: app
    app.kubernetes.io/name: astraos-app
    app.kubernetes.io/part-of: astra-os
spec:
  type: ClusterIP
  selector:
    app: astraos
    component: app
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: fpm
      port: 9000
      targetPort: 9000
      protocol: TCP
